version: "3.7"

services:
  rabbitmq:
    # Pull image from hub.docker.com
    image: rabbitmq:3.8.27-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    networks:
      - currency-compose-network

  zuul-api-gateway:
    build:
      context: netflix-zuul-api-gateway-server
      dockerfile: Dockerfile
    image: gourabix/netflix-zuul-api-gateway-server:1.1
    ports:
      - 8765:8765
    environment:
      # Default RabbitMQ username = guest, default RabbitMQ password = guest
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    restart: always
    depends_on:
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - currency-compose-network

  zipkin-server:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - 9411:9411
    environment:
      # mem = in-memory database. DO NOT USE IN PRODUCTION!
      STORAGE_TYPE: mem
      # Default RabbitMQ username = guest, default RabbitMQ password = guest
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - currency-compose-network

  naming-server:
    build:
      context: netflix-eureka-naming-server
      dockerfile: Dockerfile
    image: gourabix/netflix-eureka-naming-server:1.1
    ports:
      - 8761:8761
    restart: always
    networks:
      - currency-compose-network

  currency-exchange-service:
    build:
      context: currency-exchange-service
      dockerfile: Dockerfile
    image: gourabix/currency-exchange-service:1.1
    restart: always
    environment:
      # Default RabbitMQ username = guest, default RabbitMQ password = guest
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    # For docker-compose to dynamically scale up and down services, ports must not be statically
    # allocated to those services.
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - currency-compose-network

  currency-conversion-service:
    build:
      context: currency-conversion-service
      dockerfile: Dockerfile
    image: gourabix/currency-conversion-service:1.1
    restart: always
    ports:
      - 8100:8100
    environment:
      # not required anymore after implementation of Netflix eureka naming server and FeignClient.
      # CURRENCY_EXCHANGE_URI: http://currency-exchange-service:8000
      # Default RabbitMQ username = guest, default RabbitMQ password = guest
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - currency-exchange-service
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - currency-compose-network

networks:
  currency-compose-network:
