version: "3.7"

services:
  naming-server:
    build:
      context: netflix-eureka-naming-server
      dockerfile: Dockerfile
    image: gourabix/netflix-eureka-naming-server:1.1
    ports:
      - 8761:8761
    restart: always
    networks:
      - currency-compose-network

  currency-exchange-service:
    build:
      context: currency-exchange-service
      dockerfile: Dockerfile
    image: gourabix/currency-exchange-service:1.1
    restart: always
    # For docker-compose to dynamically scale up and down, ports must not be statically allocated.
    # ports:
    #   - 8000:8000
    depends_on:
      - naming-server
    networks:
      - currency-compose-network

  currency-conversion-service:
    build:
      context: currency-conversion-service
      dockerfile: Dockerfile
    image: gourabix/currency-conversion-service:1.1
    restart: always
    ports:
      - 8100:8100
    # not required anymore after implementation of Netflix eureka naming server and FeignClient.
    # environment:
    #   CURRENCY_EXCHANGE_URI: http://currency-exchange-service:8000
    depends_on:
      - currency-exchange-service
      - naming-server
    networks:
      - currency-compose-network

networks:
  currency-compose-network:
